# fly.toml app configuration file generated for learncrafter on 2025-07-25T18:25:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "learncrafter-mvp"
primary_region = "iad"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[mounts]
  source = "learncrafter_data"
  destination = "/data"

[processes]
  app = "uvicorn app.main:app --host 0.0.0.0 --port 8000" 